# Site settings
title: Liad Avraham
email: liad@avrah.am
description: liadav
baseurl: "/identity-jekyll-theme" # the subpath of your site, e.g. /blog
url: "liad.avrah.am" # the base hostname & protocol for your site

# Identity
your-name: Liad Avraham
your-title: liadav

# Social settings
500px_url:
facebook_url: https://www.facebook.com/liadav/
github_url: https://github.com/liadav
gitlab_url: 
googleplus_url: instagram_url: https://www.instagram.com/liadav6/
linkedin_url: https://www.linkedin.com/in/liadav/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/liadav6

# Build settings
markdown: kramdown
